project:
    artifactId: book
    name: book
    version: 1.0.0-SNAPSHOT
    description: Demo project for info endpoint

# For Spring Actuator /info endpoint
info:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

eureka:
  instance:
    # interval for periodic heartbeat to the registry; default 10
    leaseRenewalIntervalInSeconds: 10
  client:
    enabled: true
    registryFetchIntervalSeconds: 5
    # by default, Eureka uses the client heartbeat to determine if a client is up. Unless specified otherwise the
    # Discovery Client will not propagate the current health check status of the application.
    # should only be set in application.yml
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_ZONE}

# use a HTTP port 8080
server:
  port: 8080

datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
  validationQuery: SELECT 1
  initialSize: 1
  maxActive: 3
  testWhileIdle: true
  testOnBorrow: true

jpa:
  show-sql: true
  format_sql: true
  properties:
    org:
      hibernate:
        flushMode: AUTO
        entity_dirtiness_strategy: com.basaki.example.postgres.jsonb.data.strategy.EntityDirtinessStrategy
